# Generated by Django 5.1.4 on 2025-01-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_post_content_post_created_at_post_title_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='autor',
        ),
    ]
