# Generated by Django 5.1.4 on 2025-01-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_user_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='user',
        ),
    ]
